// Code generated by ent, DO NOT EDIT.

package execution

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/davidroman0O/go-tempolite/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Execution {
	return predicate.Execution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Execution {
	return predicate.Execution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Execution {
	return predicate.Execution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Execution {
	return predicate.Execution(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Execution {
	return predicate.Execution(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Execution {
	return predicate.Execution(sql.FieldContainsFold(FieldID, id))
}

// Dag applies equality check predicate on the "dag" field. It's identical to DagEQ.
func Dag(v []byte) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldDag, v))
}

// DagEQ applies the EQ predicate on the "dag" field.
func DagEQ(v []byte) predicate.Execution {
	return predicate.Execution(sql.FieldEQ(FieldDag, v))
}

// DagNEQ applies the NEQ predicate on the "dag" field.
func DagNEQ(v []byte) predicate.Execution {
	return predicate.Execution(sql.FieldNEQ(FieldDag, v))
}

// DagIn applies the In predicate on the "dag" field.
func DagIn(vs ...[]byte) predicate.Execution {
	return predicate.Execution(sql.FieldIn(FieldDag, vs...))
}

// DagNotIn applies the NotIn predicate on the "dag" field.
func DagNotIn(vs ...[]byte) predicate.Execution {
	return predicate.Execution(sql.FieldNotIn(FieldDag, vs...))
}

// DagGT applies the GT predicate on the "dag" field.
func DagGT(v []byte) predicate.Execution {
	return predicate.Execution(sql.FieldGT(FieldDag, v))
}

// DagGTE applies the GTE predicate on the "dag" field.
func DagGTE(v []byte) predicate.Execution {
	return predicate.Execution(sql.FieldGTE(FieldDag, v))
}

// DagLT applies the LT predicate on the "dag" field.
func DagLT(v []byte) predicate.Execution {
	return predicate.Execution(sql.FieldLT(FieldDag, v))
}

// DagLTE applies the LTE predicate on the "dag" field.
func DagLTE(v []byte) predicate.Execution {
	return predicate.Execution(sql.FieldLTE(FieldDag, v))
}

// HasExecutionContext applies the HasEdge predicate on the "execution_context" edge.
func HasExecutionContext() predicate.Execution {
	return predicate.Execution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ExecutionContextTable, ExecutionContextColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExecutionContextWith applies the HasEdge predicate on the "execution_context" edge with a given conditions (other predicates).
func HasExecutionContextWith(preds ...predicate.ExecutionContext) predicate.Execution {
	return predicate.Execution(func(s *sql.Selector) {
		step := newExecutionContextStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Execution) predicate.Execution {
	return predicate.Execution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Execution) predicate.Execution {
	return predicate.Execution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Execution) predicate.Execution {
	return predicate.Execution(sql.NotPredicates(p))
}
