// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ActivityData is the predicate function for activitydata builders.
type ActivityData func(*sql.Selector)

// ActivityExecution is the predicate function for activityexecution builders.
type ActivityExecution func(*sql.Selector)

// ActivityExecutionData is the predicate function for activityexecutiondata builders.
type ActivityExecutionData func(*sql.Selector)

// Entity is the predicate function for entity builders.
type Entity func(*sql.Selector)

// Execution is the predicate function for execution builders.
type Execution func(*sql.Selector)

// Hierarchy is the predicate function for hierarchy builders.
type Hierarchy func(*sql.Selector)

// Queue is the predicate function for queue builders.
type Queue func(*sql.Selector)

// Run is the predicate function for run builders.
type Run func(*sql.Selector)

// SagaData is the predicate function for sagadata builders.
type SagaData func(*sql.Selector)

// SagaExecution is the predicate function for sagaexecution builders.
type SagaExecution func(*sql.Selector)

// SagaExecutionData is the predicate function for sagaexecutiondata builders.
type SagaExecutionData func(*sql.Selector)

// SideEffectData is the predicate function for sideeffectdata builders.
type SideEffectData func(*sql.Selector)

// SideEffectExecution is the predicate function for sideeffectexecution builders.
type SideEffectExecution func(*sql.Selector)

// SideEffectExecutionData is the predicate function for sideeffectexecutiondata builders.
type SideEffectExecutionData func(*sql.Selector)

// Version is the predicate function for version builders.
type Version func(*sql.Selector)

// WorkflowData is the predicate function for workflowdata builders.
type WorkflowData func(*sql.Selector)

// WorkflowExecution is the predicate function for workflowexecution builders.
type WorkflowExecution func(*sql.Selector)

// WorkflowExecutionData is the predicate function for workflowexecutiondata builders.
type WorkflowExecutionData func(*sql.Selector)
