// Code generated by ent, DO NOT EDIT.

package executionrelationship

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the executionrelationship type in the database.
	Label = "execution_relationship"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldParentEntityID holds the string denoting the parent_entity_id field in the database.
	FieldParentEntityID = "parent_entity_id"
	// FieldChildEntityID holds the string denoting the child_entity_id field in the database.
	FieldChildEntityID = "child_entity_id"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldChildID holds the string denoting the child_id field in the database.
	FieldChildID = "child_id"
	// FieldParentType holds the string denoting the parent_type field in the database.
	FieldParentType = "parent_type"
	// FieldChildType holds the string denoting the child_type field in the database.
	FieldChildType = "child_type"
	// FieldParentStepID holds the string denoting the parent_step_id field in the database.
	FieldParentStepID = "parent_step_id"
	// FieldChildStepID holds the string denoting the child_step_id field in the database.
	FieldChildStepID = "child_step_id"
	// Table holds the table name of the executionrelationship in the database.
	Table = "execution_relationships"
)

// Columns holds all SQL columns for executionrelationship fields.
var Columns = []string{
	FieldID,
	FieldRunID,
	FieldParentEntityID,
	FieldChildEntityID,
	FieldParentID,
	FieldChildID,
	FieldParentType,
	FieldChildType,
	FieldParentStepID,
	FieldChildStepID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	RunIDValidator func(string) error
	// ParentEntityIDValidator is a validator for the "parent_entity_id" field. It is called by the builders before save.
	ParentEntityIDValidator func(string) error
	// ChildEntityIDValidator is a validator for the "child_entity_id" field. It is called by the builders before save.
	ChildEntityIDValidator func(string) error
	// ParentStepIDValidator is a validator for the "parent_step_id" field. It is called by the builders before save.
	ParentStepIDValidator func(string) error
	// ChildStepIDValidator is a validator for the "child_step_id" field. It is called by the builders before save.
	ChildStepIDValidator func(string) error
)

// ParentType defines the type for the "parent_type" enum field.
type ParentType string

// ParentType values.
const (
	ParentTypeWorkflow   ParentType = "workflow"
	ParentTypeActivity   ParentType = "activity"
	ParentTypeSaga       ParentType = "saga"
	ParentTypeSideEffect ParentType = "side_effect"
	ParentTypeYield      ParentType = "yield"
	ParentTypeSignal     ParentType = "signal"
)

func (pt ParentType) String() string {
	return string(pt)
}

// ParentTypeValidator is a validator for the "parent_type" field enum values. It is called by the builders before save.
func ParentTypeValidator(pt ParentType) error {
	switch pt {
	case ParentTypeWorkflow, ParentTypeActivity, ParentTypeSaga, ParentTypeSideEffect, ParentTypeYield, ParentTypeSignal:
		return nil
	default:
		return fmt.Errorf("executionrelationship: invalid enum value for parent_type field: %q", pt)
	}
}

// ChildType defines the type for the "child_type" enum field.
type ChildType string

// ChildType values.
const (
	ChildTypeWorkflow   ChildType = "workflow"
	ChildTypeActivity   ChildType = "activity"
	ChildTypeSaga       ChildType = "saga"
	ChildTypeSideEffect ChildType = "side_effect"
	ChildTypeYield      ChildType = "yield"
	ChildTypeSignal     ChildType = "signal"
)

func (ct ChildType) String() string {
	return string(ct)
}

// ChildTypeValidator is a validator for the "child_type" field enum values. It is called by the builders before save.
func ChildTypeValidator(ct ChildType) error {
	switch ct {
	case ChildTypeWorkflow, ChildTypeActivity, ChildTypeSaga, ChildTypeSideEffect, ChildTypeYield, ChildTypeSignal:
		return nil
	default:
		return fmt.Errorf("executionrelationship: invalid enum value for child_type field: %q", ct)
	}
}

// OrderOption defines the ordering options for the ExecutionRelationship queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByParentEntityID orders the results by the parent_entity_id field.
func ByParentEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentEntityID, opts...).ToFunc()
}

// ByChildEntityID orders the results by the child_entity_id field.
func ByChildEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChildEntityID, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByChildID orders the results by the child_id field.
func ByChildID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChildID, opts...).ToFunc()
}

// ByParentType orders the results by the parent_type field.
func ByParentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentType, opts...).ToFunc()
}

// ByChildType orders the results by the child_type field.
func ByChildType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChildType, opts...).ToFunc()
}

// ByParentStepID orders the results by the parent_step_id field.
func ByParentStepID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentStepID, opts...).ToFunc()
}

// ByChildStepID orders the results by the child_step_id field.
func ByChildStepID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChildStepID, opts...).ToFunc()
}
