// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/davidroman0O/tempolite/internal/persistence/ent/activityexecution"
	"github.com/davidroman0O/tempolite/internal/persistence/ent/activityexecutiondata"
)

// ActivityExecutionDataCreate is the builder for creating a ActivityExecutionData entity.
type ActivityExecutionDataCreate struct {
	config
	mutation *ActivityExecutionDataMutation
	hooks    []Hook
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (aedc *ActivityExecutionDataCreate) SetLastHeartbeat(t time.Time) *ActivityExecutionDataCreate {
	aedc.mutation.SetLastHeartbeat(t)
	return aedc
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (aedc *ActivityExecutionDataCreate) SetNillableLastHeartbeat(t *time.Time) *ActivityExecutionDataCreate {
	if t != nil {
		aedc.SetLastHeartbeat(*t)
	}
	return aedc
}

// SetOutputs sets the "outputs" field.
func (aedc *ActivityExecutionDataCreate) SetOutputs(u [][]uint8) *ActivityExecutionDataCreate {
	aedc.mutation.SetOutputs(u)
	return aedc
}

// SetActivityExecutionID sets the "activity_execution" edge to the ActivityExecution entity by ID.
func (aedc *ActivityExecutionDataCreate) SetActivityExecutionID(id int) *ActivityExecutionDataCreate {
	aedc.mutation.SetActivityExecutionID(id)
	return aedc
}

// SetActivityExecution sets the "activity_execution" edge to the ActivityExecution entity.
func (aedc *ActivityExecutionDataCreate) SetActivityExecution(a *ActivityExecution) *ActivityExecutionDataCreate {
	return aedc.SetActivityExecutionID(a.ID)
}

// Mutation returns the ActivityExecutionDataMutation object of the builder.
func (aedc *ActivityExecutionDataCreate) Mutation() *ActivityExecutionDataMutation {
	return aedc.mutation
}

// Save creates the ActivityExecutionData in the database.
func (aedc *ActivityExecutionDataCreate) Save(ctx context.Context) (*ActivityExecutionData, error) {
	return withHooks(ctx, aedc.sqlSave, aedc.mutation, aedc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (aedc *ActivityExecutionDataCreate) SaveX(ctx context.Context) *ActivityExecutionData {
	v, err := aedc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aedc *ActivityExecutionDataCreate) Exec(ctx context.Context) error {
	_, err := aedc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aedc *ActivityExecutionDataCreate) ExecX(ctx context.Context) {
	if err := aedc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aedc *ActivityExecutionDataCreate) check() error {
	if len(aedc.mutation.ActivityExecutionIDs()) == 0 {
		return &ValidationError{Name: "activity_execution", err: errors.New(`ent: missing required edge "ActivityExecutionData.activity_execution"`)}
	}
	return nil
}

func (aedc *ActivityExecutionDataCreate) sqlSave(ctx context.Context) (*ActivityExecutionData, error) {
	if err := aedc.check(); err != nil {
		return nil, err
	}
	_node, _spec := aedc.createSpec()
	if err := sqlgraph.CreateNode(ctx, aedc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	aedc.mutation.id = &_node.ID
	aedc.mutation.done = true
	return _node, nil
}

func (aedc *ActivityExecutionDataCreate) createSpec() (*ActivityExecutionData, *sqlgraph.CreateSpec) {
	var (
		_node = &ActivityExecutionData{config: aedc.config}
		_spec = sqlgraph.NewCreateSpec(activityexecutiondata.Table, sqlgraph.NewFieldSpec(activityexecutiondata.FieldID, field.TypeInt))
	)
	if value, ok := aedc.mutation.LastHeartbeat(); ok {
		_spec.SetField(activityexecutiondata.FieldLastHeartbeat, field.TypeTime, value)
		_node.LastHeartbeat = &value
	}
	if value, ok := aedc.mutation.Outputs(); ok {
		_spec.SetField(activityexecutiondata.FieldOutputs, field.TypeJSON, value)
		_node.Outputs = value
	}
	if nodes := aedc.mutation.ActivityExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   activityexecutiondata.ActivityExecutionTable,
			Columns: []string{activityexecutiondata.ActivityExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activityexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.activity_execution_execution_data = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ActivityExecutionDataCreateBulk is the builder for creating many ActivityExecutionData entities in bulk.
type ActivityExecutionDataCreateBulk struct {
	config
	err      error
	builders []*ActivityExecutionDataCreate
}

// Save creates the ActivityExecutionData entities in the database.
func (aedcb *ActivityExecutionDataCreateBulk) Save(ctx context.Context) ([]*ActivityExecutionData, error) {
	if aedcb.err != nil {
		return nil, aedcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(aedcb.builders))
	nodes := make([]*ActivityExecutionData, len(aedcb.builders))
	mutators := make([]Mutator, len(aedcb.builders))
	for i := range aedcb.builders {
		func(i int, root context.Context) {
			builder := aedcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityExecutionDataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aedcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aedcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aedcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aedcb *ActivityExecutionDataCreateBulk) SaveX(ctx context.Context) []*ActivityExecutionData {
	v, err := aedcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aedcb *ActivityExecutionDataCreateBulk) Exec(ctx context.Context) error {
	_, err := aedcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aedcb *ActivityExecutionDataCreateBulk) ExecX(ctx context.Context) {
	if err := aedcb.Exec(ctx); err != nil {
		panic(err)
	}
}
