// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/davidroman0O/tempolite/ent/activity"
	"github.com/davidroman0O/tempolite/ent/activityexecution"
)

// ActivityExecutionCreate is the builder for creating a ActivityExecution entity.
type ActivityExecutionCreate struct {
	config
	mutation *ActivityExecutionMutation
	hooks    []Hook
}

// SetRunID sets the "run_id" field.
func (aec *ActivityExecutionCreate) SetRunID(s string) *ActivityExecutionCreate {
	aec.mutation.SetRunID(s)
	return aec
}

// SetStatus sets the "status" field.
func (aec *ActivityExecutionCreate) SetStatus(a activityexecution.Status) *ActivityExecutionCreate {
	aec.mutation.SetStatus(a)
	return aec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (aec *ActivityExecutionCreate) SetNillableStatus(a *activityexecution.Status) *ActivityExecutionCreate {
	if a != nil {
		aec.SetStatus(*a)
	}
	return aec
}

// SetAttempt sets the "attempt" field.
func (aec *ActivityExecutionCreate) SetAttempt(i int) *ActivityExecutionCreate {
	aec.mutation.SetAttempt(i)
	return aec
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (aec *ActivityExecutionCreate) SetNillableAttempt(i *int) *ActivityExecutionCreate {
	if i != nil {
		aec.SetAttempt(*i)
	}
	return aec
}

// SetOutput sets the "output" field.
func (aec *ActivityExecutionCreate) SetOutput(u [][]uint8) *ActivityExecutionCreate {
	aec.mutation.SetOutput(u)
	return aec
}

// SetError sets the "error" field.
func (aec *ActivityExecutionCreate) SetError(s string) *ActivityExecutionCreate {
	aec.mutation.SetError(s)
	return aec
}

// SetNillableError sets the "error" field if the given value is not nil.
func (aec *ActivityExecutionCreate) SetNillableError(s *string) *ActivityExecutionCreate {
	if s != nil {
		aec.SetError(*s)
	}
	return aec
}

// SetStartedAt sets the "started_at" field.
func (aec *ActivityExecutionCreate) SetStartedAt(t time.Time) *ActivityExecutionCreate {
	aec.mutation.SetStartedAt(t)
	return aec
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (aec *ActivityExecutionCreate) SetNillableStartedAt(t *time.Time) *ActivityExecutionCreate {
	if t != nil {
		aec.SetStartedAt(*t)
	}
	return aec
}

// SetUpdatedAt sets the "updated_at" field.
func (aec *ActivityExecutionCreate) SetUpdatedAt(t time.Time) *ActivityExecutionCreate {
	aec.mutation.SetUpdatedAt(t)
	return aec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (aec *ActivityExecutionCreate) SetNillableUpdatedAt(t *time.Time) *ActivityExecutionCreate {
	if t != nil {
		aec.SetUpdatedAt(*t)
	}
	return aec
}

// SetID sets the "id" field.
func (aec *ActivityExecutionCreate) SetID(s string) *ActivityExecutionCreate {
	aec.mutation.SetID(s)
	return aec
}

// SetActivityID sets the "activity" edge to the Activity entity by ID.
func (aec *ActivityExecutionCreate) SetActivityID(id string) *ActivityExecutionCreate {
	aec.mutation.SetActivityID(id)
	return aec
}

// SetActivity sets the "activity" edge to the Activity entity.
func (aec *ActivityExecutionCreate) SetActivity(a *Activity) *ActivityExecutionCreate {
	return aec.SetActivityID(a.ID)
}

// Mutation returns the ActivityExecutionMutation object of the builder.
func (aec *ActivityExecutionCreate) Mutation() *ActivityExecutionMutation {
	return aec.mutation
}

// Save creates the ActivityExecution in the database.
func (aec *ActivityExecutionCreate) Save(ctx context.Context) (*ActivityExecution, error) {
	aec.defaults()
	return withHooks(ctx, aec.sqlSave, aec.mutation, aec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (aec *ActivityExecutionCreate) SaveX(ctx context.Context) *ActivityExecution {
	v, err := aec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aec *ActivityExecutionCreate) Exec(ctx context.Context) error {
	_, err := aec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aec *ActivityExecutionCreate) ExecX(ctx context.Context) {
	if err := aec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aec *ActivityExecutionCreate) defaults() {
	if _, ok := aec.mutation.Status(); !ok {
		v := activityexecution.DefaultStatus
		aec.mutation.SetStatus(v)
	}
	if _, ok := aec.mutation.Attempt(); !ok {
		v := activityexecution.DefaultAttempt
		aec.mutation.SetAttempt(v)
	}
	if _, ok := aec.mutation.StartedAt(); !ok {
		v := activityexecution.DefaultStartedAt()
		aec.mutation.SetStartedAt(v)
	}
	if _, ok := aec.mutation.UpdatedAt(); !ok {
		v := activityexecution.DefaultUpdatedAt()
		aec.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aec *ActivityExecutionCreate) check() error {
	if _, ok := aec.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "ActivityExecution.run_id"`)}
	}
	if _, ok := aec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ActivityExecution.status"`)}
	}
	if v, ok := aec.mutation.Status(); ok {
		if err := activityexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ActivityExecution.status": %w`, err)}
		}
	}
	if _, ok := aec.mutation.Attempt(); !ok {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required field "ActivityExecution.attempt"`)}
	}
	if _, ok := aec.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "ActivityExecution.started_at"`)}
	}
	if _, ok := aec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ActivityExecution.updated_at"`)}
	}
	if len(aec.mutation.ActivityIDs()) == 0 {
		return &ValidationError{Name: "activity", err: errors.New(`ent: missing required edge "ActivityExecution.activity"`)}
	}
	return nil
}

func (aec *ActivityExecutionCreate) sqlSave(ctx context.Context) (*ActivityExecution, error) {
	if err := aec.check(); err != nil {
		return nil, err
	}
	_node, _spec := aec.createSpec()
	if err := sqlgraph.CreateNode(ctx, aec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ActivityExecution.ID type: %T", _spec.ID.Value)
		}
	}
	aec.mutation.id = &_node.ID
	aec.mutation.done = true
	return _node, nil
}

func (aec *ActivityExecutionCreate) createSpec() (*ActivityExecution, *sqlgraph.CreateSpec) {
	var (
		_node = &ActivityExecution{config: aec.config}
		_spec = sqlgraph.NewCreateSpec(activityexecution.Table, sqlgraph.NewFieldSpec(activityexecution.FieldID, field.TypeString))
	)
	if id, ok := aec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := aec.mutation.RunID(); ok {
		_spec.SetField(activityexecution.FieldRunID, field.TypeString, value)
		_node.RunID = value
	}
	if value, ok := aec.mutation.Status(); ok {
		_spec.SetField(activityexecution.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := aec.mutation.Attempt(); ok {
		_spec.SetField(activityexecution.FieldAttempt, field.TypeInt, value)
		_node.Attempt = value
	}
	if value, ok := aec.mutation.Output(); ok {
		_spec.SetField(activityexecution.FieldOutput, field.TypeJSON, value)
		_node.Output = value
	}
	if value, ok := aec.mutation.Error(); ok {
		_spec.SetField(activityexecution.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := aec.mutation.StartedAt(); ok {
		_spec.SetField(activityexecution.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := aec.mutation.UpdatedAt(); ok {
		_spec.SetField(activityexecution.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := aec.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activityexecution.ActivityTable,
			Columns: []string{activityexecution.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.activity_executions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ActivityExecutionCreateBulk is the builder for creating many ActivityExecution entities in bulk.
type ActivityExecutionCreateBulk struct {
	config
	err      error
	builders []*ActivityExecutionCreate
}

// Save creates the ActivityExecution entities in the database.
func (aecb *ActivityExecutionCreateBulk) Save(ctx context.Context) ([]*ActivityExecution, error) {
	if aecb.err != nil {
		return nil, aecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(aecb.builders))
	nodes := make([]*ActivityExecution, len(aecb.builders))
	mutators := make([]Mutator, len(aecb.builders))
	for i := range aecb.builders {
		func(i int, root context.Context) {
			builder := aecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aecb *ActivityExecutionCreateBulk) SaveX(ctx context.Context) []*ActivityExecution {
	v, err := aecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aecb *ActivityExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := aecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aecb *ActivityExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := aecb.Exec(ctx); err != nil {
		panic(err)
	}
}
