// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/davidroman0O/go-tempolite/ent/compensationtask"
	"github.com/davidroman0O/go-tempolite/ent/node"
)

// CompensationTask is the model entity for the CompensationTask schema.
type CompensationTask struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CompensationTaskQuery when eager-loading is set.
	Edges                  CompensationTaskEdges `json:"edges"`
	node_compensation_task *string
	selectValues           sql.SelectValues
}

// CompensationTaskEdges holds the relations/edges for other nodes in the graph.
type CompensationTaskEdges struct {
	// Node holds the value of the node edge.
	Node *Node `json:"node,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NodeOrErr returns the Node value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CompensationTaskEdges) NodeOrErr() (*Node, error) {
	if e.Node != nil {
		return e.Node, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "node"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CompensationTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case compensationtask.FieldID:
			values[i] = new(sql.NullInt64)
		case compensationtask.ForeignKeys[0]: // node_compensation_task
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CompensationTask fields.
func (ct *CompensationTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case compensationtask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ct.ID = int(value.Int64)
		case compensationtask.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_compensation_task", values[i])
			} else if value.Valid {
				ct.node_compensation_task = new(string)
				*ct.node_compensation_task = value.String
			}
		default:
			ct.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CompensationTask.
// This includes values selected through modifiers, order, etc.
func (ct *CompensationTask) Value(name string) (ent.Value, error) {
	return ct.selectValues.Get(name)
}

// QueryNode queries the "node" edge of the CompensationTask entity.
func (ct *CompensationTask) QueryNode() *NodeQuery {
	return NewCompensationTaskClient(ct.config).QueryNode(ct)
}

// Update returns a builder for updating this CompensationTask.
// Note that you need to call CompensationTask.Unwrap() before calling this method if this CompensationTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (ct *CompensationTask) Update() *CompensationTaskUpdateOne {
	return NewCompensationTaskClient(ct.config).UpdateOne(ct)
}

// Unwrap unwraps the CompensationTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ct *CompensationTask) Unwrap() *CompensationTask {
	_tx, ok := ct.config.driver.(*txDriver)
	if !ok {
		panic("ent: CompensationTask is not a transactional entity")
	}
	ct.config.driver = _tx.drv
	return ct
}

// String implements the fmt.Stringer.
func (ct *CompensationTask) String() string {
	var builder strings.Builder
	builder.WriteString("CompensationTask(")
	builder.WriteString(fmt.Sprintf("id=%v", ct.ID))
	builder.WriteByte(')')
	return builder.String()
}

// CompensationTasks is a parsable slice of CompensationTask.
type CompensationTasks []*CompensationTask
