// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/davidroman0O/go-tempolite/ent/sagaexecution"
	"github.com/davidroman0O/go-tempolite/ent/sagastepexecution"
)

// SagaStepExecutionCreate is the builder for creating a SagaStepExecution entity.
type SagaStepExecutionCreate struct {
	config
	mutation *SagaStepExecutionMutation
	hooks    []Hook
}

// SetHandlerName sets the "handler_name" field.
func (ssec *SagaStepExecutionCreate) SetHandlerName(s string) *SagaStepExecutionCreate {
	ssec.mutation.SetHandlerName(s)
	return ssec
}

// SetStepType sets the "step_type" field.
func (ssec *SagaStepExecutionCreate) SetStepType(st sagastepexecution.StepType) *SagaStepExecutionCreate {
	ssec.mutation.SetStepType(st)
	return ssec
}

// SetStatus sets the "status" field.
func (ssec *SagaStepExecutionCreate) SetStatus(s sagastepexecution.Status) *SagaStepExecutionCreate {
	ssec.mutation.SetStatus(s)
	return ssec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ssec *SagaStepExecutionCreate) SetNillableStatus(s *sagastepexecution.Status) *SagaStepExecutionCreate {
	if s != nil {
		ssec.SetStatus(*s)
	}
	return ssec
}

// SetSequence sets the "sequence" field.
func (ssec *SagaStepExecutionCreate) SetSequence(i int) *SagaStepExecutionCreate {
	ssec.mutation.SetSequence(i)
	return ssec
}

// SetAttempt sets the "attempt" field.
func (ssec *SagaStepExecutionCreate) SetAttempt(i int) *SagaStepExecutionCreate {
	ssec.mutation.SetAttempt(i)
	return ssec
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (ssec *SagaStepExecutionCreate) SetNillableAttempt(i *int) *SagaStepExecutionCreate {
	if i != nil {
		ssec.SetAttempt(*i)
	}
	return ssec
}

// SetInput sets the "input" field.
func (ssec *SagaStepExecutionCreate) SetInput(i []interface{}) *SagaStepExecutionCreate {
	ssec.mutation.SetInput(i)
	return ssec
}

// SetOutput sets the "output" field.
func (ssec *SagaStepExecutionCreate) SetOutput(i []interface{}) *SagaStepExecutionCreate {
	ssec.mutation.SetOutput(i)
	return ssec
}

// SetStartedAt sets the "started_at" field.
func (ssec *SagaStepExecutionCreate) SetStartedAt(t time.Time) *SagaStepExecutionCreate {
	ssec.mutation.SetStartedAt(t)
	return ssec
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (ssec *SagaStepExecutionCreate) SetNillableStartedAt(t *time.Time) *SagaStepExecutionCreate {
	if t != nil {
		ssec.SetStartedAt(*t)
	}
	return ssec
}

// SetUpdatedAt sets the "updated_at" field.
func (ssec *SagaStepExecutionCreate) SetUpdatedAt(t time.Time) *SagaStepExecutionCreate {
	ssec.mutation.SetUpdatedAt(t)
	return ssec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ssec *SagaStepExecutionCreate) SetNillableUpdatedAt(t *time.Time) *SagaStepExecutionCreate {
	if t != nil {
		ssec.SetUpdatedAt(*t)
	}
	return ssec
}

// SetID sets the "id" field.
func (ssec *SagaStepExecutionCreate) SetID(s string) *SagaStepExecutionCreate {
	ssec.mutation.SetID(s)
	return ssec
}

// SetSagaExecutionID sets the "saga_execution" edge to the SagaExecution entity by ID.
func (ssec *SagaStepExecutionCreate) SetSagaExecutionID(id string) *SagaStepExecutionCreate {
	ssec.mutation.SetSagaExecutionID(id)
	return ssec
}

// SetSagaExecution sets the "saga_execution" edge to the SagaExecution entity.
func (ssec *SagaStepExecutionCreate) SetSagaExecution(s *SagaExecution) *SagaStepExecutionCreate {
	return ssec.SetSagaExecutionID(s.ID)
}

// Mutation returns the SagaStepExecutionMutation object of the builder.
func (ssec *SagaStepExecutionCreate) Mutation() *SagaStepExecutionMutation {
	return ssec.mutation
}

// Save creates the SagaStepExecution in the database.
func (ssec *SagaStepExecutionCreate) Save(ctx context.Context) (*SagaStepExecution, error) {
	ssec.defaults()
	return withHooks(ctx, ssec.sqlSave, ssec.mutation, ssec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ssec *SagaStepExecutionCreate) SaveX(ctx context.Context) *SagaStepExecution {
	v, err := ssec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ssec *SagaStepExecutionCreate) Exec(ctx context.Context) error {
	_, err := ssec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssec *SagaStepExecutionCreate) ExecX(ctx context.Context) {
	if err := ssec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssec *SagaStepExecutionCreate) defaults() {
	if _, ok := ssec.mutation.Status(); !ok {
		v := sagastepexecution.DefaultStatus
		ssec.mutation.SetStatus(v)
	}
	if _, ok := ssec.mutation.Attempt(); !ok {
		v := sagastepexecution.DefaultAttempt
		ssec.mutation.SetAttempt(v)
	}
	if _, ok := ssec.mutation.StartedAt(); !ok {
		v := sagastepexecution.DefaultStartedAt()
		ssec.mutation.SetStartedAt(v)
	}
	if _, ok := ssec.mutation.UpdatedAt(); !ok {
		v := sagastepexecution.DefaultUpdatedAt()
		ssec.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ssec *SagaStepExecutionCreate) check() error {
	if _, ok := ssec.mutation.HandlerName(); !ok {
		return &ValidationError{Name: "handler_name", err: errors.New(`ent: missing required field "SagaStepExecution.handler_name"`)}
	}
	if v, ok := ssec.mutation.HandlerName(); ok {
		if err := sagastepexecution.HandlerNameValidator(v); err != nil {
			return &ValidationError{Name: "handler_name", err: fmt.Errorf(`ent: validator failed for field "SagaStepExecution.handler_name": %w`, err)}
		}
	}
	if _, ok := ssec.mutation.StepType(); !ok {
		return &ValidationError{Name: "step_type", err: errors.New(`ent: missing required field "SagaStepExecution.step_type"`)}
	}
	if v, ok := ssec.mutation.StepType(); ok {
		if err := sagastepexecution.StepTypeValidator(v); err != nil {
			return &ValidationError{Name: "step_type", err: fmt.Errorf(`ent: validator failed for field "SagaStepExecution.step_type": %w`, err)}
		}
	}
	if _, ok := ssec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SagaStepExecution.status"`)}
	}
	if v, ok := ssec.mutation.Status(); ok {
		if err := sagastepexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SagaStepExecution.status": %w`, err)}
		}
	}
	if _, ok := ssec.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "SagaStepExecution.sequence"`)}
	}
	if v, ok := ssec.mutation.Sequence(); ok {
		if err := sagastepexecution.SequenceValidator(v); err != nil {
			return &ValidationError{Name: "sequence", err: fmt.Errorf(`ent: validator failed for field "SagaStepExecution.sequence": %w`, err)}
		}
	}
	if _, ok := ssec.mutation.Attempt(); !ok {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required field "SagaStepExecution.attempt"`)}
	}
	if _, ok := ssec.mutation.Input(); !ok {
		return &ValidationError{Name: "input", err: errors.New(`ent: missing required field "SagaStepExecution.input"`)}
	}
	if _, ok := ssec.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "SagaStepExecution.started_at"`)}
	}
	if _, ok := ssec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SagaStepExecution.updated_at"`)}
	}
	if len(ssec.mutation.SagaExecutionIDs()) == 0 {
		return &ValidationError{Name: "saga_execution", err: errors.New(`ent: missing required edge "SagaStepExecution.saga_execution"`)}
	}
	return nil
}

func (ssec *SagaStepExecutionCreate) sqlSave(ctx context.Context) (*SagaStepExecution, error) {
	if err := ssec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ssec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ssec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SagaStepExecution.ID type: %T", _spec.ID.Value)
		}
	}
	ssec.mutation.id = &_node.ID
	ssec.mutation.done = true
	return _node, nil
}

func (ssec *SagaStepExecutionCreate) createSpec() (*SagaStepExecution, *sqlgraph.CreateSpec) {
	var (
		_node = &SagaStepExecution{config: ssec.config}
		_spec = sqlgraph.NewCreateSpec(sagastepexecution.Table, sqlgraph.NewFieldSpec(sagastepexecution.FieldID, field.TypeString))
	)
	if id, ok := ssec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ssec.mutation.HandlerName(); ok {
		_spec.SetField(sagastepexecution.FieldHandlerName, field.TypeString, value)
		_node.HandlerName = value
	}
	if value, ok := ssec.mutation.StepType(); ok {
		_spec.SetField(sagastepexecution.FieldStepType, field.TypeEnum, value)
		_node.StepType = value
	}
	if value, ok := ssec.mutation.Status(); ok {
		_spec.SetField(sagastepexecution.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ssec.mutation.Sequence(); ok {
		_spec.SetField(sagastepexecution.FieldSequence, field.TypeInt, value)
		_node.Sequence = value
	}
	if value, ok := ssec.mutation.Attempt(); ok {
		_spec.SetField(sagastepexecution.FieldAttempt, field.TypeInt, value)
		_node.Attempt = value
	}
	if value, ok := ssec.mutation.Input(); ok {
		_spec.SetField(sagastepexecution.FieldInput, field.TypeJSON, value)
		_node.Input = value
	}
	if value, ok := ssec.mutation.Output(); ok {
		_spec.SetField(sagastepexecution.FieldOutput, field.TypeJSON, value)
		_node.Output = value
	}
	if value, ok := ssec.mutation.StartedAt(); ok {
		_spec.SetField(sagastepexecution.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := ssec.mutation.UpdatedAt(); ok {
		_spec.SetField(sagastepexecution.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := ssec.mutation.SagaExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sagastepexecution.SagaExecutionTable,
			Columns: []string{sagastepexecution.SagaExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sagaexecution.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.saga_execution_steps = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SagaStepExecutionCreateBulk is the builder for creating many SagaStepExecution entities in bulk.
type SagaStepExecutionCreateBulk struct {
	config
	err      error
	builders []*SagaStepExecutionCreate
}

// Save creates the SagaStepExecution entities in the database.
func (ssecb *SagaStepExecutionCreateBulk) Save(ctx context.Context) ([]*SagaStepExecution, error) {
	if ssecb.err != nil {
		return nil, ssecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ssecb.builders))
	nodes := make([]*SagaStepExecution, len(ssecb.builders))
	mutators := make([]Mutator, len(ssecb.builders))
	for i := range ssecb.builders {
		func(i int, root context.Context) {
			builder := ssecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SagaStepExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ssecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ssecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ssecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ssecb *SagaStepExecutionCreateBulk) SaveX(ctx context.Context) []*SagaStepExecution {
	v, err := ssecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ssecb *SagaStepExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := ssecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssecb *SagaStepExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := ssecb.Exec(ctx); err != nil {
		panic(err)
	}
}
