// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/davidroman0O/tempolite/ent/sagaentity"
	"github.com/davidroman0O/tempolite/ent/sagaexecution"
	"github.com/davidroman0O/tempolite/ent/sagaexecutiondata"
	"github.com/davidroman0O/tempolite/ent/sagavalue"
	"github.com/davidroman0O/tempolite/ent/schema"
)

// SagaExecutionCreate is the builder for creating a SagaExecution entity.
type SagaExecutionCreate struct {
	config
	mutation *SagaExecutionMutation
	hooks    []Hook
}

// SetSagaEntityID sets the "saga_entity_id" field.
func (sec *SagaExecutionCreate) SetSagaEntityID(sei schema.SagaEntityID) *SagaExecutionCreate {
	sec.mutation.SetSagaEntityID(sei)
	return sec
}

// SetExecutionType sets the "execution_type" field.
func (sec *SagaExecutionCreate) SetExecutionType(st schema.ExecutionType) *SagaExecutionCreate {
	sec.mutation.SetExecutionType(st)
	return sec
}

// SetNillableExecutionType sets the "execution_type" field if the given value is not nil.
func (sec *SagaExecutionCreate) SetNillableExecutionType(st *schema.ExecutionType) *SagaExecutionCreate {
	if st != nil {
		sec.SetExecutionType(*st)
	}
	return sec
}

// SetStartedAt sets the "started_at" field.
func (sec *SagaExecutionCreate) SetStartedAt(t time.Time) *SagaExecutionCreate {
	sec.mutation.SetStartedAt(t)
	return sec
}

// SetCompletedAt sets the "completed_at" field.
func (sec *SagaExecutionCreate) SetCompletedAt(t time.Time) *SagaExecutionCreate {
	sec.mutation.SetCompletedAt(t)
	return sec
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (sec *SagaExecutionCreate) SetNillableCompletedAt(t *time.Time) *SagaExecutionCreate {
	if t != nil {
		sec.SetCompletedAt(*t)
	}
	return sec
}

// SetStatus sets the "status" field.
func (sec *SagaExecutionCreate) SetStatus(ss schema.ExecutionStatus) *SagaExecutionCreate {
	sec.mutation.SetStatus(ss)
	return sec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sec *SagaExecutionCreate) SetNillableStatus(ss *schema.ExecutionStatus) *SagaExecutionCreate {
	if ss != nil {
		sec.SetStatus(*ss)
	}
	return sec
}

// SetError sets the "error" field.
func (sec *SagaExecutionCreate) SetError(s string) *SagaExecutionCreate {
	sec.mutation.SetError(s)
	return sec
}

// SetNillableError sets the "error" field if the given value is not nil.
func (sec *SagaExecutionCreate) SetNillableError(s *string) *SagaExecutionCreate {
	if s != nil {
		sec.SetError(*s)
	}
	return sec
}

// SetStackTrace sets the "stack_trace" field.
func (sec *SagaExecutionCreate) SetStackTrace(s string) *SagaExecutionCreate {
	sec.mutation.SetStackTrace(s)
	return sec
}

// SetNillableStackTrace sets the "stack_trace" field if the given value is not nil.
func (sec *SagaExecutionCreate) SetNillableStackTrace(s *string) *SagaExecutionCreate {
	if s != nil {
		sec.SetStackTrace(*s)
	}
	return sec
}

// SetCreatedAt sets the "created_at" field.
func (sec *SagaExecutionCreate) SetCreatedAt(t time.Time) *SagaExecutionCreate {
	sec.mutation.SetCreatedAt(t)
	return sec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sec *SagaExecutionCreate) SetNillableCreatedAt(t *time.Time) *SagaExecutionCreate {
	if t != nil {
		sec.SetCreatedAt(*t)
	}
	return sec
}

// SetUpdatedAt sets the "updated_at" field.
func (sec *SagaExecutionCreate) SetUpdatedAt(t time.Time) *SagaExecutionCreate {
	sec.mutation.SetUpdatedAt(t)
	return sec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sec *SagaExecutionCreate) SetNillableUpdatedAt(t *time.Time) *SagaExecutionCreate {
	if t != nil {
		sec.SetUpdatedAt(*t)
	}
	return sec
}

// SetID sets the "id" field.
func (sec *SagaExecutionCreate) SetID(sei schema.SagaExecutionID) *SagaExecutionCreate {
	sec.mutation.SetID(sei)
	return sec
}

// SetSagaID sets the "saga" edge to the SagaEntity entity by ID.
func (sec *SagaExecutionCreate) SetSagaID(id schema.SagaEntityID) *SagaExecutionCreate {
	sec.mutation.SetSagaID(id)
	return sec
}

// SetSaga sets the "saga" edge to the SagaEntity entity.
func (sec *SagaExecutionCreate) SetSaga(s *SagaEntity) *SagaExecutionCreate {
	return sec.SetSagaID(s.ID)
}

// SetExecutionDataID sets the "execution_data" edge to the SagaExecutionData entity by ID.
func (sec *SagaExecutionCreate) SetExecutionDataID(id schema.SagaExecutionDataID) *SagaExecutionCreate {
	sec.mutation.SetExecutionDataID(id)
	return sec
}

// SetNillableExecutionDataID sets the "execution_data" edge to the SagaExecutionData entity by ID if the given value is not nil.
func (sec *SagaExecutionCreate) SetNillableExecutionDataID(id *schema.SagaExecutionDataID) *SagaExecutionCreate {
	if id != nil {
		sec = sec.SetExecutionDataID(*id)
	}
	return sec
}

// SetExecutionData sets the "execution_data" edge to the SagaExecutionData entity.
func (sec *SagaExecutionCreate) SetExecutionData(s *SagaExecutionData) *SagaExecutionCreate {
	return sec.SetExecutionDataID(s.ID)
}

// AddValueIDs adds the "values" edge to the SagaValue entity by IDs.
func (sec *SagaExecutionCreate) AddValueIDs(ids ...schema.SagaValueID) *SagaExecutionCreate {
	sec.mutation.AddValueIDs(ids...)
	return sec
}

// AddValues adds the "values" edges to the SagaValue entity.
func (sec *SagaExecutionCreate) AddValues(s ...*SagaValue) *SagaExecutionCreate {
	ids := make([]schema.SagaValueID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sec.AddValueIDs(ids...)
}

// Mutation returns the SagaExecutionMutation object of the builder.
func (sec *SagaExecutionCreate) Mutation() *SagaExecutionMutation {
	return sec.mutation
}

// Save creates the SagaExecution in the database.
func (sec *SagaExecutionCreate) Save(ctx context.Context) (*SagaExecution, error) {
	sec.defaults()
	return withHooks(ctx, sec.sqlSave, sec.mutation, sec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sec *SagaExecutionCreate) SaveX(ctx context.Context) *SagaExecution {
	v, err := sec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sec *SagaExecutionCreate) Exec(ctx context.Context) error {
	_, err := sec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sec *SagaExecutionCreate) ExecX(ctx context.Context) {
	if err := sec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sec *SagaExecutionCreate) defaults() {
	if _, ok := sec.mutation.ExecutionType(); !ok {
		v := sagaexecution.DefaultExecutionType
		sec.mutation.SetExecutionType(v)
	}
	if _, ok := sec.mutation.Status(); !ok {
		v := sagaexecution.DefaultStatus
		sec.mutation.SetStatus(v)
	}
	if _, ok := sec.mutation.CreatedAt(); !ok {
		v := sagaexecution.DefaultCreatedAt()
		sec.mutation.SetCreatedAt(v)
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		v := sagaexecution.DefaultUpdatedAt()
		sec.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sec *SagaExecutionCreate) check() error {
	if _, ok := sec.mutation.SagaEntityID(); !ok {
		return &ValidationError{Name: "saga_entity_id", err: errors.New(`ent: missing required field "SagaExecution.saga_entity_id"`)}
	}
	if _, ok := sec.mutation.ExecutionType(); !ok {
		return &ValidationError{Name: "execution_type", err: errors.New(`ent: missing required field "SagaExecution.execution_type"`)}
	}
	if _, ok := sec.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "SagaExecution.started_at"`)}
	}
	if _, ok := sec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SagaExecution.status"`)}
	}
	if _, ok := sec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SagaExecution.created_at"`)}
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SagaExecution.updated_at"`)}
	}
	if len(sec.mutation.SagaIDs()) == 0 {
		return &ValidationError{Name: "saga", err: errors.New(`ent: missing required edge "SagaExecution.saga"`)}
	}
	return nil
}

func (sec *SagaExecutionCreate) sqlSave(ctx context.Context) (*SagaExecution, error) {
	if err := sec.check(); err != nil {
		return nil, err
	}
	_node, _spec := sec.createSpec()
	if err := sqlgraph.CreateNode(ctx, sec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = schema.SagaExecutionID(id)
	}
	sec.mutation.id = &_node.ID
	sec.mutation.done = true
	return _node, nil
}

func (sec *SagaExecutionCreate) createSpec() (*SagaExecution, *sqlgraph.CreateSpec) {
	var (
		_node = &SagaExecution{config: sec.config}
		_spec = sqlgraph.NewCreateSpec(sagaexecution.Table, sqlgraph.NewFieldSpec(sagaexecution.FieldID, field.TypeInt))
	)
	if id, ok := sec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sec.mutation.ExecutionType(); ok {
		_spec.SetField(sagaexecution.FieldExecutionType, field.TypeString, value)
		_node.ExecutionType = value
	}
	if value, ok := sec.mutation.StartedAt(); ok {
		_spec.SetField(sagaexecution.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := sec.mutation.CompletedAt(); ok {
		_spec.SetField(sagaexecution.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := sec.mutation.Status(); ok {
		_spec.SetField(sagaexecution.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := sec.mutation.Error(); ok {
		_spec.SetField(sagaexecution.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := sec.mutation.StackTrace(); ok {
		_spec.SetField(sagaexecution.FieldStackTrace, field.TypeString, value)
		_node.StackTrace = value
	}
	if value, ok := sec.mutation.CreatedAt(); ok {
		_spec.SetField(sagaexecution.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sec.mutation.UpdatedAt(); ok {
		_spec.SetField(sagaexecution.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := sec.mutation.SagaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sagaexecution.SagaTable,
			Columns: []string{sagaexecution.SagaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sagaentity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SagaEntityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sec.mutation.ExecutionDataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sagaexecution.ExecutionDataTable,
			Columns: []string{sagaexecution.ExecutionDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sagaexecutiondata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sec.mutation.ValuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sagaexecution.ValuesTable,
			Columns: []string{sagaexecution.ValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sagavalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SagaExecutionCreateBulk is the builder for creating many SagaExecution entities in bulk.
type SagaExecutionCreateBulk struct {
	config
	err      error
	builders []*SagaExecutionCreate
}

// Save creates the SagaExecution entities in the database.
func (secb *SagaExecutionCreateBulk) Save(ctx context.Context) ([]*SagaExecution, error) {
	if secb.err != nil {
		return nil, secb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(secb.builders))
	nodes := make([]*SagaExecution, len(secb.builders))
	mutators := make([]Mutator, len(secb.builders))
	for i := range secb.builders {
		func(i int, root context.Context) {
			builder := secb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SagaExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, secb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, secb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = schema.SagaExecutionID(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, secb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (secb *SagaExecutionCreateBulk) SaveX(ctx context.Context) []*SagaExecution {
	v, err := secb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (secb *SagaExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := secb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (secb *SagaExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := secb.Exec(ctx); err != nil {
		panic(err)
	}
}
