// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/davidroman0O/go-tempolite/ent/node"
	"github.com/davidroman0O/go-tempolite/ent/sagatask"
)

// SagaTask is the model entity for the SagaTask schema.
type SagaTask struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SagaTaskQuery when eager-loading is set.
	Edges               SagaTaskEdges `json:"edges"`
	node_saga_step_task *string
	selectValues        sql.SelectValues
}

// SagaTaskEdges holds the relations/edges for other nodes in the graph.
type SagaTaskEdges struct {
	// Node holds the value of the node edge.
	Node *Node `json:"node,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NodeOrErr returns the Node value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SagaTaskEdges) NodeOrErr() (*Node, error) {
	if e.Node != nil {
		return e.Node, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "node"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SagaTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sagatask.FieldID:
			values[i] = new(sql.NullInt64)
		case sagatask.ForeignKeys[0]: // node_saga_step_task
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SagaTask fields.
func (st *SagaTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sagatask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			st.ID = int(value.Int64)
		case sagatask.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_saga_step_task", values[i])
			} else if value.Valid {
				st.node_saga_step_task = new(string)
				*st.node_saga_step_task = value.String
			}
		default:
			st.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SagaTask.
// This includes values selected through modifiers, order, etc.
func (st *SagaTask) Value(name string) (ent.Value, error) {
	return st.selectValues.Get(name)
}

// QueryNode queries the "node" edge of the SagaTask entity.
func (st *SagaTask) QueryNode() *NodeQuery {
	return NewSagaTaskClient(st.config).QueryNode(st)
}

// Update returns a builder for updating this SagaTask.
// Note that you need to call SagaTask.Unwrap() before calling this method if this SagaTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (st *SagaTask) Update() *SagaTaskUpdateOne {
	return NewSagaTaskClient(st.config).UpdateOne(st)
}

// Unwrap unwraps the SagaTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (st *SagaTask) Unwrap() *SagaTask {
	_tx, ok := st.config.driver.(*txDriver)
	if !ok {
		panic("ent: SagaTask is not a transactional entity")
	}
	st.config.driver = _tx.drv
	return st
}

// String implements the fmt.Stringer.
func (st *SagaTask) String() string {
	var builder strings.Builder
	builder.WriteString("SagaTask(")
	builder.WriteString(fmt.Sprintf("id=%v", st.ID))
	builder.WriteByte(')')
	return builder.String()
}

// SagaTasks is a parsable slice of SagaTask.
type SagaTasks []*SagaTask
