// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/davidroman0O/tempolite/ent/predicate"
	"github.com/davidroman0O/tempolite/ent/signal"
	"github.com/davidroman0O/tempolite/ent/signalexecution"
)

// SignalExecutionQuery is the builder for querying SignalExecution entities.
type SignalExecutionQuery struct {
	config
	ctx        *QueryContext
	order      []signalexecution.OrderOption
	inters     []Interceptor
	predicates []predicate.SignalExecution
	withSignal *SignalQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SignalExecutionQuery builder.
func (seq *SignalExecutionQuery) Where(ps ...predicate.SignalExecution) *SignalExecutionQuery {
	seq.predicates = append(seq.predicates, ps...)
	return seq
}

// Limit the number of records to be returned by this query.
func (seq *SignalExecutionQuery) Limit(limit int) *SignalExecutionQuery {
	seq.ctx.Limit = &limit
	return seq
}

// Offset to start from.
func (seq *SignalExecutionQuery) Offset(offset int) *SignalExecutionQuery {
	seq.ctx.Offset = &offset
	return seq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (seq *SignalExecutionQuery) Unique(unique bool) *SignalExecutionQuery {
	seq.ctx.Unique = &unique
	return seq
}

// Order specifies how the records should be ordered.
func (seq *SignalExecutionQuery) Order(o ...signalexecution.OrderOption) *SignalExecutionQuery {
	seq.order = append(seq.order, o...)
	return seq
}

// QuerySignal chains the current query on the "signal" edge.
func (seq *SignalExecutionQuery) QuerySignal() *SignalQuery {
	query := (&SignalClient{config: seq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := seq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := seq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(signalexecution.Table, signalexecution.FieldID, selector),
			sqlgraph.To(signal.Table, signal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, signalexecution.SignalTable, signalexecution.SignalColumn),
		)
		fromU = sqlgraph.SetNeighbors(seq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SignalExecution entity from the query.
// Returns a *NotFoundError when no SignalExecution was found.
func (seq *SignalExecutionQuery) First(ctx context.Context) (*SignalExecution, error) {
	nodes, err := seq.Limit(1).All(setContextOp(ctx, seq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{signalexecution.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (seq *SignalExecutionQuery) FirstX(ctx context.Context) *SignalExecution {
	node, err := seq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SignalExecution ID from the query.
// Returns a *NotFoundError when no SignalExecution ID was found.
func (seq *SignalExecutionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = seq.Limit(1).IDs(setContextOp(ctx, seq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{signalexecution.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (seq *SignalExecutionQuery) FirstIDX(ctx context.Context) string {
	id, err := seq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SignalExecution entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SignalExecution entity is found.
// Returns a *NotFoundError when no SignalExecution entities are found.
func (seq *SignalExecutionQuery) Only(ctx context.Context) (*SignalExecution, error) {
	nodes, err := seq.Limit(2).All(setContextOp(ctx, seq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{signalexecution.Label}
	default:
		return nil, &NotSingularError{signalexecution.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (seq *SignalExecutionQuery) OnlyX(ctx context.Context) *SignalExecution {
	node, err := seq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SignalExecution ID in the query.
// Returns a *NotSingularError when more than one SignalExecution ID is found.
// Returns a *NotFoundError when no entities are found.
func (seq *SignalExecutionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = seq.Limit(2).IDs(setContextOp(ctx, seq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{signalexecution.Label}
	default:
		err = &NotSingularError{signalexecution.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (seq *SignalExecutionQuery) OnlyIDX(ctx context.Context) string {
	id, err := seq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SignalExecutions.
func (seq *SignalExecutionQuery) All(ctx context.Context) ([]*SignalExecution, error) {
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryAll)
	if err := seq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SignalExecution, *SignalExecutionQuery]()
	return withInterceptors[[]*SignalExecution](ctx, seq, qr, seq.inters)
}

// AllX is like All, but panics if an error occurs.
func (seq *SignalExecutionQuery) AllX(ctx context.Context) []*SignalExecution {
	nodes, err := seq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SignalExecution IDs.
func (seq *SignalExecutionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if seq.ctx.Unique == nil && seq.path != nil {
		seq.Unique(true)
	}
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryIDs)
	if err = seq.Select(signalexecution.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (seq *SignalExecutionQuery) IDsX(ctx context.Context) []string {
	ids, err := seq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (seq *SignalExecutionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryCount)
	if err := seq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, seq, querierCount[*SignalExecutionQuery](), seq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (seq *SignalExecutionQuery) CountX(ctx context.Context) int {
	count, err := seq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (seq *SignalExecutionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryExist)
	switch _, err := seq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (seq *SignalExecutionQuery) ExistX(ctx context.Context) bool {
	exist, err := seq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SignalExecutionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (seq *SignalExecutionQuery) Clone() *SignalExecutionQuery {
	if seq == nil {
		return nil
	}
	return &SignalExecutionQuery{
		config:     seq.config,
		ctx:        seq.ctx.Clone(),
		order:      append([]signalexecution.OrderOption{}, seq.order...),
		inters:     append([]Interceptor{}, seq.inters...),
		predicates: append([]predicate.SignalExecution{}, seq.predicates...),
		withSignal: seq.withSignal.Clone(),
		// clone intermediate query.
		sql:  seq.sql.Clone(),
		path: seq.path,
	}
}

// WithSignal tells the query-builder to eager-load the nodes that are connected to
// the "signal" edge. The optional arguments are used to configure the query builder of the edge.
func (seq *SignalExecutionQuery) WithSignal(opts ...func(*SignalQuery)) *SignalExecutionQuery {
	query := (&SignalClient{config: seq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	seq.withSignal = query
	return seq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RunID string `json:"run_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SignalExecution.Query().
//		GroupBy(signalexecution.FieldRunID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (seq *SignalExecutionQuery) GroupBy(field string, fields ...string) *SignalExecutionGroupBy {
	seq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SignalExecutionGroupBy{build: seq}
	grbuild.flds = &seq.ctx.Fields
	grbuild.label = signalexecution.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RunID string `json:"run_id,omitempty"`
//	}
//
//	client.SignalExecution.Query().
//		Select(signalexecution.FieldRunID).
//		Scan(ctx, &v)
func (seq *SignalExecutionQuery) Select(fields ...string) *SignalExecutionSelect {
	seq.ctx.Fields = append(seq.ctx.Fields, fields...)
	sbuild := &SignalExecutionSelect{SignalExecutionQuery: seq}
	sbuild.label = signalexecution.Label
	sbuild.flds, sbuild.scan = &seq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SignalExecutionSelect configured with the given aggregations.
func (seq *SignalExecutionQuery) Aggregate(fns ...AggregateFunc) *SignalExecutionSelect {
	return seq.Select().Aggregate(fns...)
}

func (seq *SignalExecutionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range seq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, seq); err != nil {
				return err
			}
		}
	}
	for _, f := range seq.ctx.Fields {
		if !signalexecution.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if seq.path != nil {
		prev, err := seq.path(ctx)
		if err != nil {
			return err
		}
		seq.sql = prev
	}
	return nil
}

func (seq *SignalExecutionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SignalExecution, error) {
	var (
		nodes       = []*SignalExecution{}
		withFKs     = seq.withFKs
		_spec       = seq.querySpec()
		loadedTypes = [1]bool{
			seq.withSignal != nil,
		}
	)
	if seq.withSignal != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, signalexecution.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SignalExecution).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SignalExecution{config: seq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, seq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := seq.withSignal; query != nil {
		if err := seq.loadSignal(ctx, query, nodes, nil,
			func(n *SignalExecution, e *Signal) { n.Edges.Signal = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (seq *SignalExecutionQuery) loadSignal(ctx context.Context, query *SignalQuery, nodes []*SignalExecution, init func(*SignalExecution), assign func(*SignalExecution, *Signal)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*SignalExecution)
	for i := range nodes {
		if nodes[i].signal_executions == nil {
			continue
		}
		fk := *nodes[i].signal_executions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(signal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "signal_executions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (seq *SignalExecutionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := seq.querySpec()
	_spec.Node.Columns = seq.ctx.Fields
	if len(seq.ctx.Fields) > 0 {
		_spec.Unique = seq.ctx.Unique != nil && *seq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, seq.driver, _spec)
}

func (seq *SignalExecutionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(signalexecution.Table, signalexecution.Columns, sqlgraph.NewFieldSpec(signalexecution.FieldID, field.TypeString))
	_spec.From = seq.sql
	if unique := seq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if seq.path != nil {
		_spec.Unique = true
	}
	if fields := seq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signalexecution.FieldID)
		for i := range fields {
			if fields[i] != signalexecution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := seq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := seq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := seq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := seq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (seq *SignalExecutionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(seq.driver.Dialect())
	t1 := builder.Table(signalexecution.Table)
	columns := seq.ctx.Fields
	if len(columns) == 0 {
		columns = signalexecution.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if seq.sql != nil {
		selector = seq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if seq.ctx.Unique != nil && *seq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range seq.predicates {
		p(selector)
	}
	for _, p := range seq.order {
		p(selector)
	}
	if offset := seq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := seq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SignalExecutionGroupBy is the group-by builder for SignalExecution entities.
type SignalExecutionGroupBy struct {
	selector
	build *SignalExecutionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (segb *SignalExecutionGroupBy) Aggregate(fns ...AggregateFunc) *SignalExecutionGroupBy {
	segb.fns = append(segb.fns, fns...)
	return segb
}

// Scan applies the selector query and scans the result into the given value.
func (segb *SignalExecutionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, segb.build.ctx, ent.OpQueryGroupBy)
	if err := segb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SignalExecutionQuery, *SignalExecutionGroupBy](ctx, segb.build, segb, segb.build.inters, v)
}

func (segb *SignalExecutionGroupBy) sqlScan(ctx context.Context, root *SignalExecutionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(segb.fns))
	for _, fn := range segb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*segb.flds)+len(segb.fns))
		for _, f := range *segb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*segb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := segb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SignalExecutionSelect is the builder for selecting fields of SignalExecution entities.
type SignalExecutionSelect struct {
	*SignalExecutionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ses *SignalExecutionSelect) Aggregate(fns ...AggregateFunc) *SignalExecutionSelect {
	ses.fns = append(ses.fns, fns...)
	return ses
}

// Scan applies the selector query and scans the result into the given value.
func (ses *SignalExecutionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ses.ctx, ent.OpQuerySelect)
	if err := ses.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SignalExecutionQuery, *SignalExecutionSelect](ctx, ses.SignalExecutionQuery, ses, ses.inters, v)
}

func (ses *SignalExecutionSelect) sqlScan(ctx context.Context, root *SignalExecutionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ses.fns))
	for _, fn := range ses.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ses.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ses.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
