// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/davidroman0O/tempolite/ent/schema"
	"github.com/davidroman0O/tempolite/ent/signaldata"
	"github.com/davidroman0O/tempolite/ent/signalentity"
	"github.com/davidroman0O/tempolite/ent/signalexecution"
)

// SignalEntityCreate is the builder for creating a SignalEntity entity.
type SignalEntityCreate struct {
	config
	mutation *SignalEntityMutation
	hooks    []Hook
}

// SetHandlerName sets the "handler_name" field.
func (sec *SignalEntityCreate) SetHandlerName(s string) *SignalEntityCreate {
	sec.mutation.SetHandlerName(s)
	return sec
}

// SetType sets the "type" field.
func (sec *SignalEntityCreate) SetType(st schema.EntityType) *SignalEntityCreate {
	sec.mutation.SetType(st)
	return sec
}

// SetNillableType sets the "type" field if the given value is not nil.
func (sec *SignalEntityCreate) SetNillableType(st *schema.EntityType) *SignalEntityCreate {
	if st != nil {
		sec.SetType(*st)
	}
	return sec
}

// SetStatus sets the "status" field.
func (sec *SignalEntityCreate) SetStatus(ss schema.EntityStatus) *SignalEntityCreate {
	sec.mutation.SetStatus(ss)
	return sec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sec *SignalEntityCreate) SetNillableStatus(ss *schema.EntityStatus) *SignalEntityCreate {
	if ss != nil {
		sec.SetStatus(*ss)
	}
	return sec
}

// SetStepID sets the "step_id" field.
func (sec *SignalEntityCreate) SetStepID(ssi schema.SignalStepID) *SignalEntityCreate {
	sec.mutation.SetStepID(ssi)
	return sec
}

// SetRunID sets the "run_id" field.
func (sec *SignalEntityCreate) SetRunID(si schema.RunID) *SignalEntityCreate {
	sec.mutation.SetRunID(si)
	return sec
}

// SetRetryPolicy sets the "retry_policy" field.
func (sec *SignalEntityCreate) SetRetryPolicy(sp schema.RetryPolicy) *SignalEntityCreate {
	sec.mutation.SetRetryPolicy(sp)
	return sec
}

// SetRetryState sets the "retry_state" field.
func (sec *SignalEntityCreate) SetRetryState(ss schema.RetryState) *SignalEntityCreate {
	sec.mutation.SetRetryState(ss)
	return sec
}

// SetCreatedAt sets the "created_at" field.
func (sec *SignalEntityCreate) SetCreatedAt(t time.Time) *SignalEntityCreate {
	sec.mutation.SetCreatedAt(t)
	return sec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sec *SignalEntityCreate) SetNillableCreatedAt(t *time.Time) *SignalEntityCreate {
	if t != nil {
		sec.SetCreatedAt(*t)
	}
	return sec
}

// SetUpdatedAt sets the "updated_at" field.
func (sec *SignalEntityCreate) SetUpdatedAt(t time.Time) *SignalEntityCreate {
	sec.mutation.SetUpdatedAt(t)
	return sec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sec *SignalEntityCreate) SetNillableUpdatedAt(t *time.Time) *SignalEntityCreate {
	if t != nil {
		sec.SetUpdatedAt(*t)
	}
	return sec
}

// SetID sets the "id" field.
func (sec *SignalEntityCreate) SetID(sei schema.SignalEntityID) *SignalEntityCreate {
	sec.mutation.SetID(sei)
	return sec
}

// SetSignalDataID sets the "signal_data" edge to the SignalData entity by ID.
func (sec *SignalEntityCreate) SetSignalDataID(id schema.SignalDataID) *SignalEntityCreate {
	sec.mutation.SetSignalDataID(id)
	return sec
}

// SetNillableSignalDataID sets the "signal_data" edge to the SignalData entity by ID if the given value is not nil.
func (sec *SignalEntityCreate) SetNillableSignalDataID(id *schema.SignalDataID) *SignalEntityCreate {
	if id != nil {
		sec = sec.SetSignalDataID(*id)
	}
	return sec
}

// SetSignalData sets the "signal_data" edge to the SignalData entity.
func (sec *SignalEntityCreate) SetSignalData(s *SignalData) *SignalEntityCreate {
	return sec.SetSignalDataID(s.ID)
}

// AddExecutionIDs adds the "executions" edge to the SignalExecution entity by IDs.
func (sec *SignalEntityCreate) AddExecutionIDs(ids ...schema.SignalExecutionID) *SignalEntityCreate {
	sec.mutation.AddExecutionIDs(ids...)
	return sec
}

// AddExecutions adds the "executions" edges to the SignalExecution entity.
func (sec *SignalEntityCreate) AddExecutions(s ...*SignalExecution) *SignalEntityCreate {
	ids := make([]schema.SignalExecutionID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sec.AddExecutionIDs(ids...)
}

// Mutation returns the SignalEntityMutation object of the builder.
func (sec *SignalEntityCreate) Mutation() *SignalEntityMutation {
	return sec.mutation
}

// Save creates the SignalEntity in the database.
func (sec *SignalEntityCreate) Save(ctx context.Context) (*SignalEntity, error) {
	sec.defaults()
	return withHooks(ctx, sec.sqlSave, sec.mutation, sec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sec *SignalEntityCreate) SaveX(ctx context.Context) *SignalEntity {
	v, err := sec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sec *SignalEntityCreate) Exec(ctx context.Context) error {
	_, err := sec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sec *SignalEntityCreate) ExecX(ctx context.Context) {
	if err := sec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sec *SignalEntityCreate) defaults() {
	if _, ok := sec.mutation.GetType(); !ok {
		v := signalentity.DefaultType
		sec.mutation.SetType(v)
	}
	if _, ok := sec.mutation.Status(); !ok {
		v := signalentity.DefaultStatus
		sec.mutation.SetStatus(v)
	}
	if _, ok := sec.mutation.CreatedAt(); !ok {
		v := signalentity.DefaultCreatedAt()
		sec.mutation.SetCreatedAt(v)
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		v := signalentity.DefaultUpdatedAt()
		sec.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sec *SignalEntityCreate) check() error {
	if _, ok := sec.mutation.HandlerName(); !ok {
		return &ValidationError{Name: "handler_name", err: errors.New(`ent: missing required field "SignalEntity.handler_name"`)}
	}
	if _, ok := sec.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SignalEntity.type"`)}
	}
	if _, ok := sec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SignalEntity.status"`)}
	}
	if _, ok := sec.mutation.StepID(); !ok {
		return &ValidationError{Name: "step_id", err: errors.New(`ent: missing required field "SignalEntity.step_id"`)}
	}
	if _, ok := sec.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "SignalEntity.run_id"`)}
	}
	if _, ok := sec.mutation.RetryPolicy(); !ok {
		return &ValidationError{Name: "retry_policy", err: errors.New(`ent: missing required field "SignalEntity.retry_policy"`)}
	}
	if _, ok := sec.mutation.RetryState(); !ok {
		return &ValidationError{Name: "retry_state", err: errors.New(`ent: missing required field "SignalEntity.retry_state"`)}
	}
	if _, ok := sec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SignalEntity.created_at"`)}
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SignalEntity.updated_at"`)}
	}
	return nil
}

func (sec *SignalEntityCreate) sqlSave(ctx context.Context) (*SignalEntity, error) {
	if err := sec.check(); err != nil {
		return nil, err
	}
	_node, _spec := sec.createSpec()
	if err := sqlgraph.CreateNode(ctx, sec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = schema.SignalEntityID(id)
	}
	sec.mutation.id = &_node.ID
	sec.mutation.done = true
	return _node, nil
}

func (sec *SignalEntityCreate) createSpec() (*SignalEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &SignalEntity{config: sec.config}
		_spec = sqlgraph.NewCreateSpec(signalentity.Table, sqlgraph.NewFieldSpec(signalentity.FieldID, field.TypeInt))
	)
	if id, ok := sec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sec.mutation.HandlerName(); ok {
		_spec.SetField(signalentity.FieldHandlerName, field.TypeString, value)
		_node.HandlerName = value
	}
	if value, ok := sec.mutation.GetType(); ok {
		_spec.SetField(signalentity.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := sec.mutation.Status(); ok {
		_spec.SetField(signalentity.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := sec.mutation.StepID(); ok {
		_spec.SetField(signalentity.FieldStepID, field.TypeString, value)
		_node.StepID = value
	}
	if value, ok := sec.mutation.RunID(); ok {
		_spec.SetField(signalentity.FieldRunID, field.TypeInt, value)
		_node.RunID = value
	}
	if value, ok := sec.mutation.RetryPolicy(); ok {
		_spec.SetField(signalentity.FieldRetryPolicy, field.TypeJSON, value)
		_node.RetryPolicy = value
	}
	if value, ok := sec.mutation.RetryState(); ok {
		_spec.SetField(signalentity.FieldRetryState, field.TypeJSON, value)
		_node.RetryState = value
	}
	if value, ok := sec.mutation.CreatedAt(); ok {
		_spec.SetField(signalentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sec.mutation.UpdatedAt(); ok {
		_spec.SetField(signalentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := sec.mutation.SignalDataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   signalentity.SignalDataTable,
			Columns: []string{signalentity.SignalDataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(signaldata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sec.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   signalentity.ExecutionsTable,
			Columns: []string{signalentity.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(signalexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SignalEntityCreateBulk is the builder for creating many SignalEntity entities in bulk.
type SignalEntityCreateBulk struct {
	config
	err      error
	builders []*SignalEntityCreate
}

// Save creates the SignalEntity entities in the database.
func (secb *SignalEntityCreateBulk) Save(ctx context.Context) ([]*SignalEntity, error) {
	if secb.err != nil {
		return nil, secb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(secb.builders))
	nodes := make([]*SignalEntity, len(secb.builders))
	mutators := make([]Mutator, len(secb.builders))
	for i := range secb.builders {
		func(i int, root context.Context) {
			builder := secb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SignalEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, secb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, secb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = schema.SignalEntityID(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, secb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (secb *SignalEntityCreateBulk) SaveX(ctx context.Context) []*SignalEntity {
	v, err := secb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (secb *SignalEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := secb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (secb *SignalEntityCreateBulk) ExecX(ctx context.Context) {
	if err := secb.Exec(ctx); err != nil {
		panic(err)
	}
}
